# Generated by Django 6.0.1 on 2026-01-30 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_client', models.BooleanField(default=True, verbose_name='Cliente Ativo')),
                ('plan_type', models.CharField(default='Standard', max_length=50, verbose_name='Plano Contratado')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Dados do Dashboard (JSON)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
