# Generated by Django 6.0.1 on 2026-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='client_excels/', verbose_name='Upload da Planilha (.xlsx)'),
        ),
    ]
