# Generated by Django 6.0.1 on 2026-02-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientprofile_excel_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='data_snapshot',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_active_client',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='client_csvs/', verbose_name='Upload CSV (Lote)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='wine_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Banco de Dados (JSON)'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
