# Generated by Django 6.0.1 on 2026-02-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_clientprofile_data_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_only', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('ADD', 'Adicionou Vinho'), ('REMOVE', 'Removeu Vinho'), ('CONSUME', 'Bebeu/Baixou'), ('IMPORT', 'Importação em Massa')], max_length=20)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Vinho')),
                ('vintage', models.CharField(max_length=4, verbose_name='Safra')),
                ('country', models.CharField(default='Outros', max_length=100, verbose_name='País')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Região')),
                ('type', models.CharField(default='Tinto', max_length=50, verbose_name='Tipo (Tinto/Branco/etc)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Estimado')),
                ('quantity', models.IntegerField(default=1, verbose_name='Estoque')),
                ('score_rp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Robert Parker')),
                ('score_ws', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Wine Spectator')),
                ('drink_window_start', models.IntegerField(blank=True, null=True, verbose_name='Beber de')),
                ('drink_window_end', models.IntegerField(blank=True, null=True, verbose_name='Beber até')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
