# Generated by Django 6.0.1 on 2026-02-04 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_wine_delete_clientprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['country', 'region', 'name'], 'verbose_name': 'Vinho', 'verbose_name_plural': 'Vinhos'},
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='drink_window_start',
            new_name='drink_from',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='drink_window_end',
            new_name='drink_to',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='moderator_only',
        ),
        migrations.AddField(
            model_name='wine',
            name='sub_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Região (ex: Pauillac)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ADD', 'Adicionou'), ('REMOVE', 'Removeu'), ('EDIT', 'Editou')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço (Unit)'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Garrafas'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Região (ex: Bordeaux)'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='score_rp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RP'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='score_ws',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='WS'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('Tinto', 'Tinto'), ('Branco', 'Branco'), ('Rosé', 'Rosé'), ('Espumante', 'Espumante'), ('Fortificado', 'Fortificado'), ('Sobremesa', 'Sobremesa')], default='Tinto', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.CharField(max_length=10, verbose_name='Safra'),
        ),
    ]
